services:
  ttv-archiver:
    build: .
    container_name: ttv-archiver
    restart: unless-stopped
    volumes:
      - ./cookies:/app/cookies
    environment:
      PYTHONUNBUFFERED: 1
      streamer: juunnnnnnnnnnnnnas
      yt_privacy: PUBLIC
